cabal-version:       2.4

name:                nix-tree
synopsis:            Interactively browse a Nix store paths dependencies
description:         A terminal curses application to browse a Nix store paths dependencies
version:             0.8.0
homepage:            https://github.com/utdemir/nix-tree
license:             BSD-3-Clause
license-file:        LICENSE
author:              Utku Demir
maintainer:          Utku Demir
copyright:           Utku Demir
category:            Language.Nix
build-type:          Simple
extra-source-files:  README.md, CHANGELOG.md

common common-options
  ghc-options:        -threaded
                      -Wall -Wpartial-fields -Wincomplete-record-updates -Widentities
  default-language:   Haskell2010
  default-extensions: LambdaCase
                      OverloadedStrings
                      TupleSections
                      TypeApplications
                      GeneralizedNewtypeDeriving
                      DeriveGeneric
                      DeriveFunctor
                      DerivingStrategies
                      DeriveAnyClass
                      FlexibleInstances
                      DeriveLift
                      StandaloneDeriving
                      DataKinds
                      KindSignatures
                      NamedFieldPuns
                      RankNTypes
                      ScopedTypeVariables
                      NumericUnderscores
                      MultiWayIf
                      TemplateHaskell
  mixins:             base hiding (Prelude)
                    , relude (Relude as Prelude)
  build-depends:      base >=4.11 && < 5
                    , relude
                    , containers
                    , clock
                    , filepath
                    , hrfsize
                    , text
                    , typed-process
                    , vty
                    , directory
                    , optparse-applicative
                    , microlens

library
  import:             common-options
  hs-source-dirs:     src
  exposed-modules:    NixTree.PathStats
                      NixTree.StorePath
                      NixTree.Data.InvertedIndex
  build-depends:      aeson
                    , bytestring
                    , unordered-containers
                    , dot

executable nix-tree
  import:             common-options
  ghc-options:        -Wunused-packages -threaded -with-rtsopts=-N
  main-is:            Main.hs
  hs-source-dirs:     app
  other-modules:      NixTree.BrickApp
                      NixTree.Clipboard
  default-language:   Haskell2010
  build-depends:      terminal-progress-bar
                    , async
                    , brick >= 2.1
                    , nix-tree

test-suite nix-tree-tests
  import:           common-options
  type:             exitcode-stdio-1.0
  hs-source-dirs:   test
  other-modules:    Test.NixTree.Data.InvertedIndex
  main-is:          Test.hs
  build-depends:    hedgehog
                  , nix-tree
